# Generated by Django 3.0.6 on 2021-11-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDiseaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('imgurl', models.TextField()),
                ('detail', models.TextField()),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'main_disease_list',
                'managed': False,
            },
        ),
    ]
