# Generated by Django 3.0.6 on 2020-05-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.CharField(max_length=10)),
                ('account', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('doctor_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctor_auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthPassport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('time', models.DateTimeField()),
                ('passport', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health_passport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=15)),
                ('user_id', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
