# Generated by Django 3.0.6 on 2020-05-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_analysisoddsratio_pathwayforor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytoscapeJsonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('oddsratio', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'cytoscape_json_config',
                'managed': False,
            },
        ),
    ]
