# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '14.0'

target 'LunSenLu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LunSenLu
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Zip', '~> 2.1'
  pod 'SSZipArchive'
  pod 'CryptoSwift', '~> 1.3.8'
  
  pod 'BottomSheet', :git => 'https://github.com/weitieda/bottom-sheet.git'
  
  pod 'KeychainAccess'

  target 'LunSenLuTests' do
    inherit! :search_paths
    # Pods for testing
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'Zip', '~> 2.1'

    pod 'CryptoSwift', '~> 1.3.8'
    
    pod 'BottomSheet', :git => 'https://github.com/weitieda/bottom-sheet.git'
    
    pod 'KeychainAccess'
  end

  target 'LunSenLuUITests' do
    # Pods for testing
  end

end
